Add `stdlib.extract` and `stdlib.patch`.
raven-os/nbuild pull request #27
Opened 2019-03-14 04:03 UTC by Arignir

2019-03-14 15:59 UTC, Pedrochu submitted a review, later dismissed

2019-03-18 01:34 UTC, doom requested changes

2019-03-18 01:34 UTC, doom commented on stdlib/patch.py
> +    """Apply the patch pointed by ``path`` on the code base.
```suggestion
    """Apply the patch pointed to by ``path`` on the code base.
```

2019-03-18 01:34 UTC, doom commented on stdlib/patch.py
> +    stdlib.cmd(f'patch -Np1 -i {path}')
Maybe document the function like `as-if performing patch with <options>`

2019-03-18 01:34 UTC, doom commented on stdlib/patch.py
> +    :note: The patches must be ``.patch`` file to be automatically picked up by this function.
```suggestion
    :note: The patches must be ``.patch`` files to be automatically picked up by this function.
```

2019-03-18 04:54 UTC, doom approved these changes

2019-03-18 04:54 UTC, merged